name = "vinayakkulkarni"
main = "./.output/server/index.mjs"
minify = true
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2022-09-10"

rules = [{ type = "ESModule", globs = ["**/*.js", "**/*.mjs"] }]

[site]
bucket = ".output/public"
